apiVersion: v1
kind: Pod
namespace: dabaghi
metadata:
  name: random-number-generator
  labels:
    name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    commmand: ["/bin/bash", "-c"]
    arg: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume

  volumes:
  - name: data-volume
    hostPath:
      path: /data
      type: Directory